import { SampleRecord } from '../types';

export const INITIAL_SAMPLES: SampleRecord[] = [
  {
    id: 'SMP-2026-081',
    caseId: 'CAS-2026-081',
    accessionNumber: 'ACC-84920-1',
    barcode: 'BAR-849201',
    patient: {
      patientId: 'PAT-MRN-84920',
      mrn: 'MRN-84920',
      fullName: 'أحمد عبد الله الغامدي',
      birthDate: '1984-06-15',
      age: 41,
      gender: 'male',
      email: 'ahmed.patient@pantissue.ai',
      phone: '+966 50 123 4567',
    },
    order: {
      caseId: 'CAS-2026-081',
      accessionNumber: 'ACC-84920-1',
      orderingDepartment: 'قسم أمراض وزراعة الكلى',
      orderingProvider: 'د. فيصل الشهري',
      clinicalNote: 'فحص نسيجي نانومتري ثلاثي الأبعاد لتقييم كفاءة النسيج الكلوي الوظيفي واستبعاد التليف الخلالي.',
      priority: 'routine',
      createdAt: '2026-03-01T09:30:00Z',
    },
    specimenType: 'خزعة كلوية إبرية (Renal Core Biopsy)',
    anatomicalSite: 'الكلى اليمنى (Right Kidney - Cortex & Medulla)',
    anatomicalSide: 'right',
    containerBlockId: 'BLK-K08',
    collectionAt: '2026-03-01T08:15:00Z',
    receivedAt: '2026-03-01T09:00:00Z',
    acceptanceStatus: 'accepted',
    processingStatus: 'completed',
    quality: {
      fixativeType: '10% Neutral Buffered Formalin',
      fixationDuration: '90 دقيقة',
      prepMethod: 'تثبيت نانوي وتقطيع متسلسل عالي الدقة',
      vhhPanel: 'PanTissue-VHH NanoMarker #4 (Podocyte/Glomerular Panel)',
      labelType: 'Fluorophore AlexaFluor-647',
      incubationMinutes: 45,
      qcStatus: 'passed',
      snr: 24.8,
      artifacts: 'لا توجد تشوهات أو طيات شريطية',
      qcDecision: 'continue',
    },
    scanRun: {
      scanRunId: 'SR-99214',
      scannerId: 'PanTissue Optical Scanner 3D-Pro (SN: SC-882)',
      scannedAt: '2026-03-01T11:20:00Z',
      wavelength: '647 nm Ex / 670 nm Em',
      voxelSize: '0.25 × 0.25 × 0.5 µm³',
      sliceCount: 64,
      totalScanVolume: 14.5,
      signalIntensityRange: '18 - 250 RFU',
      preprocessingAlgorithm: 'Gaussian Filtering / Dynamic Normalization',
      segmentationModel: '3D U-Net TissueSegmenter v0.9.0',
      surfaceAlgorithm: 'Marching Cubes Surface Mesh',
    },
    quantitative: {
      totalVolume: 14.5,
      healthyVolume: 11.83,
      damagedVolume: 2.67,
      transitionVolume: 1.74,
      unclassifiedVolume: 0.0,
      healthyPercent: 81.6,
      damagedPercent: 18.4,
      daiPercent: 18.4,
      daiCategory: 'low',
      damageLevel: 'mild',
      spatialPattern: 'focal',
      mostAffectedCoordinate: 'X: 34.1, Y: 82.5, Z: 21.0 (القطب العلوي)',
      affectedFociCount: 1,
      averageConfidence: 95.2,
      uncertaintyLevel: 'low',
      measurements: [
        { id: 'C-01', type: 'Cell', volume: 135.2, x: 34.1, y: 82.5, z: 21.0, confidence: 96, status: 'reviewed', tissueClass: 'healthy' },
        { id: 'C-02', type: 'Cell', volume: 112.4, x: 38.0, y: 79.2, z: 25.4, confidence: 94, status: 'reviewed', tissueClass: 'healthy' },
        { id: 'V-01', type: 'Vessel', volume: 2200.5, x: 115.0, y: 65.0, z: 38.0, confidence: 93, status: 'reviewed', tissueClass: 'healthy' },
        { id: 'C-03', type: 'Cell', volume: 85.0, x: 42.1, y: 90.3, z: 18.2, confidence: 88, status: 'reviewed', tissueClass: 'transition' },
        { id: 'R-01', type: 'Region', volume: 450.0, x: 28.0, y: 105.0, z: 30.0, confidence: 82, status: 'reviewed', tissueClass: 'damaged' },
      ],
    },
    review: {
      pathologistComment: 'النسيج الكلوي يظهر بنية وظيفية ممتازة بنسبة 81.6%. الكبيبات الكلوية سليمة ولا توجد علامات ضمور أنبوبي حاد أو تليف خلالي متقدم. التغيرات البؤرية طفيفة ومستقرة سريرياً.',
      preliminaryImpression: 'مؤشر الضمور الرقمي DAI منخفض (18.4%) - حالة نسيجية سليمة ومستقرة.',
      recommendation: 'استمرار المتابعة الدورية السنوية دون الحاجة إلى تدخل علاجي مكثف في الوقت الراهن.',
      reviewStatus: 'approved',
      reviewedBy: 'د. سارة أحمد (استشارية علم الأمراض)',
      reviewedAt: '2026-03-01T14:30:00Z',
      approvedBy: 'د. سارة أحمد',
      approvedAt: '2026-03-01T15:00:00Z',
      digitalSignature: 'SIG-PT-SA-9824-20260301-VERIFIED',
    },
    auditTrail: [
      {
        id: 'aud-81-1',
        sampleId: 'SMP-2026-081',
        action: 'اعتماد التقرير النسيجي النهائي والأرشفة السريرية',
        actorName: 'د. سارة أحمد',
        actorRole: 'pathologist',
        timestamp: '2026-03-01T15:00:00Z',
        details: 'تم التدقيق والاعتماد الرقمي ونشر التقرير.',
      },
    ],
    isDraft: false,
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-03-01T15:00:00Z',
  },
  {
    id: 'SMP-2026-094',
    caseId: 'CAS-2026-094',
    accessionNumber: 'ACC-84920-2',
    barcode: 'BAR-849202',
    patient: {
      patientId: 'PAT-MRN-84920',
      mrn: 'MRN-84920',
      fullName: 'أحمد عبد الله الغامدي',
      birthDate: '1984-06-15',
      age: 41,
      gender: 'male',
      email: 'ahmed.patient@pantissue.ai',
      phone: '+966 50 123 4567',
    },
    order: {
      caseId: 'CAS-2026-094',
      accessionNumber: 'ACC-84920-2',
      orderingDepartment: 'قسم أمراض وزراعة الكلى',
      orderingProvider: 'د. فيصل الشهري',
      clinicalNote: 'فحص دوري مقطعي للأنسجة المحيطة.',
      priority: 'routine',
      createdAt: '2026-03-07T10:00:00Z',
    },
    specimenType: 'مسحة جزيئية متقدمة (Molecular Cytology)',
    anatomicalSite: 'الكلى اليمنى - القطب السفلي',
    anatomicalSide: 'right',
    containerBlockId: 'BLK-K09',
    collectionAt: '2026-03-07T08:30:00Z',
    receivedAt: '2026-03-07T09:15:00Z',
    acceptanceStatus: 'accepted',
    processingStatus: 'analyzing',
    quality: {
      fixativeType: '10% Neutral Buffered Formalin',
      fixationDuration: '60 دقيقة',
      prepMethod: 'تحضير نانوي سريع',
      vhhPanel: 'PanTissue-VHH NanoMarker #4',
      labelType: 'Fluorophore AlexaFluor-647',
      incubationMinutes: 40,
      qcStatus: 'passed',
      snr: 21.0,
      artifacts: 'لا يوجد',
      qcDecision: 'continue',
    },
    review: {
      pathologistComment: '',
      preliminaryImpression: 'العينة قيد المعالجة المقطعية والتحليل ثلاثي الأبعاد بالذكاء الاصطناعي.',
      recommendation: 'في انتظار اكتمال التجزئة النسيجية وحساب مؤشر DAI.',
      reviewStatus: 'pending',
    },
    auditTrail: [
      {
        id: 'aud-94-1',
        sampleId: 'SMP-2026-094',
        action: 'استلام العينة وبدء المسح النانوي',
        actorName: 'م. يوسف الغامدي',
        actorRole: 'technician',
        timestamp: '2026-03-07T09:20:00Z',
      },
    ],
    isDraft: false,
    createdAt: '2026-03-07T09:15:00Z',
    updatedAt: '2026-03-07T09:20:00Z',
  },
  {
    id: 'SMP-2026-052',
    caseId: 'CAS-2026-052',
    accessionNumber: 'ACC-72145-1',
    barcode: 'BAR-721451',
    patient: {
      patientId: 'PAT-MRN-72145',
      mrn: 'MRN-72145',
      fullName: 'نورة عبد الرحمن السالم',
      birthDate: '1978-11-20',
      age: 47,
      gender: 'female',
      email: 'noura.patient@pantissue.ai',
      phone: '+966 55 987 6543',
    },
    order: {
      caseId: 'CAS-2026-052',
      accessionNumber: 'ACC-72145-1',
      orderingDepartment: 'قسم أمراض الجهاز الهضمي والكبد',
      orderingProvider: 'د. منيرة القحطاني',
      clinicalNote: 'تقييم التليف والضمور الكبدي بدقة الميكرون ثلاثية الأبعاد.',
      priority: 'stat',
      createdAt: '2026-02-20T11:00:00Z',
    },
    specimenType: 'خزعة كبدية جزيئية (Liver Core Needle Biopsy)',
    anatomicalSite: 'الكبد - الفص الأيمن (Liver Right Lobe Segment VI)',
    anatomicalSide: 'right',
    containerBlockId: 'BLK-L14',
    collectionAt: '2026-02-20T10:15:00Z',
    receivedAt: '2026-02-20T10:45:00Z',
    acceptanceStatus: 'accepted',
    processingStatus: 'completed',
    quality: {
      fixativeType: '10% Neutral Buffered Formalin',
      fixationDuration: '120 دقيقة',
      prepMethod: 'تثبيت نانومتري فائق الدقة',
      vhhPanel: 'PanTissue-VHH HepatoMarker #2',
      labelType: 'Fluorophore AlexaFluor-647',
      incubationMinutes: 45,
      qcStatus: 'passed',
      snr: 23.5,
      artifacts: 'لا يوجد',
      qcDecision: 'continue',
    },
    scanRun: {
      scanRunId: 'SR-77312',
      scannerId: 'PanTissue Optical Scanner 3D-Pro (SN: SC-882)',
      scannedAt: '2026-02-20T12:30:00Z',
      wavelength: '647 nm Ex / 670 nm Em',
      voxelSize: '0.25 × 0.25 × 0.5 µm³',
      sliceCount: 64,
      totalScanVolume: 16.2,
      signalIntensityRange: '15 - 240 RFU',
      preprocessingAlgorithm: 'Gaussian Filtering / Dynamic Normalization',
      segmentationModel: '3D U-Net TissueSegmenter v0.9.0',
      surfaceAlgorithm: 'Marching Cubes Surface Mesh',
    },
    quantitative: {
      totalVolume: 16.2,
      healthyVolume: 10.66,
      damagedVolume: 5.54,
      transitionVolume: 1.94,
      unclassifiedVolume: 0.0,
      healthyPercent: 65.8,
      damagedPercent: 34.2,
      daiPercent: 34.2,
      daiCategory: 'moderate',
      damageLevel: 'moderate',
      spatialPattern: 'multifocal',
      mostAffectedCoordinate: 'X: 52.4, Y: 78.1, Z: 28.3 (المنطقة البوابية)',
      affectedFociCount: 2,
      averageConfidence: 93.8,
      uncertaintyLevel: 'low',
      measurements: [
        { id: 'C-101', type: 'Cell', volume: 120.5, x: 52.4, y: 78.1, z: 28.3, confidence: 95, status: 'reviewed', tissueClass: 'healthy' },
        { id: 'C-102', type: 'Cell', volume: 95.2, x: 58.0, y: 74.0, z: 31.0, confidence: 90, status: 'reviewed', tissueClass: 'transition' },
        { id: 'V-101', type: 'Vessel', volume: 3100.0, x: 100.0, y: 70.0, z: 45.0, confidence: 94, status: 'reviewed', tissueClass: 'healthy' },
        { id: 'R-101', type: 'Region', volume: 890.0, x: 45.0, y: 88.0, z: 32.0, confidence: 86, status: 'reviewed', tissueClass: 'damaged' },
      ],
    },
    review: {
      pathologistComment: 'تُظهر نتائج الفحص النسيجي ثلاثي الأبعاد وجود تغيرات ضمورية ليفية معتدلة (DAI 34.2%) مع بقاء النسيج الوظيفي الفعال بنسبة 65.8%. البنية النسيجية مستقرة وقابلة للتحسن مع البروتوكول العلاجي المناسب.',
      preliminaryImpression: 'مؤشر الضمور الرقمي DAI معتدل (34.2%)، تغيرات بؤرية متعددة قابلة للتعويض.',
      recommendation: 'متابعة سريرية بعد 6 أشهر مع فحص إنزيمات الكبد والالتزام بالحمية الموصوفة.',
      reviewStatus: 'approved',
      reviewedBy: 'د. سارة أحمد (استشارية علم الأمراض)',
      reviewedAt: '2026-02-20T16:00:00Z',
      approvedBy: 'د. سارة أحمد',
      approvedAt: '2026-02-20T16:30:00Z',
      digitalSignature: 'SIG-PT-SA-9824-20260220-VERIFIED',
    },
    auditTrail: [
      {
        id: 'aud-52-1',
        sampleId: 'SMP-2026-052',
        action: 'اعتماد التقرير النسيجي والأرشفة الطبية',
        actorName: 'د. سارة أحمد',
        actorRole: 'pathologist',
        timestamp: '2026-02-20T16:30:00Z',
      },
    ],
    isDraft: false,
    createdAt: '2026-02-20T10:45:00Z',
    updatedAt: '2026-02-20T16:30:00Z',
  },
  {
    id: 'SMP-2026-033',
    caseId: 'CAS-2026-033',
    accessionNumber: 'ACC-55319-1',
    barcode: 'BAR-553191',
    patient: {
      patientId: 'PAT-MRN-55319',
      mrn: 'MRN-55319',
      fullName: 'خالد بن سعيد الزهراني',
      birthDate: '1969-08-10',
      age: 56,
      gender: 'male',
      email: 'khaled.patient@pantissue.ai',
      phone: '+966 54 321 0987',
    },
    order: {
      caseId: 'CAS-2026-033',
      accessionNumber: 'ACC-55319-1',
      orderingDepartment: 'قسم جراحة الأورام والبنكرياس',
      orderingProvider: 'د. طارق الحازمي',
      clinicalNote: 'فحص مجهري جزيئي ثلاثي الأبعاد لكتلة في رأس البنكرياس.',
      priority: 'stat',
      createdAt: '2026-01-15T08:00:00Z',
    },
    specimenType: 'خزعة إبرية دقيقة (Fine Needle Aspiration / Core)',
    anatomicalSite: 'رأس البنكرياس (Head of Pancreas)',
    anatomicalSide: 'not_applicable',
    containerBlockId: 'BLK-P03',
    collectionAt: '2026-01-15T07:30:00Z',
    receivedAt: '2026-01-15T08:15:00Z',
    acceptanceStatus: 'accepted',
    processingStatus: 'completed',
    quality: {
      fixativeType: '10% Neutral Buffered Formalin',
      fixationDuration: '90 دقيقة',
      prepMethod: 'تثبيت نانوي فائق',
      vhhPanel: 'PanTissue-VHH PancreatoMarker #1',
      labelType: 'Fluorophore AlexaFluor-647',
      incubationMinutes: 45,
      qcStatus: 'passed',
      snr: 20.2,
      artifacts: 'لا يوجد',
      qcDecision: 'continue',
    },
    scanRun: {
      scanRunId: 'SR-44102',
      scannerId: 'PanTissue Optical Scanner 3D-Pro (SN: SC-882)',
      scannedAt: '2026-01-15T10:00:00Z',
      wavelength: '647 nm Ex / 670 nm Em',
      voxelSize: '0.25 × 0.25 × 0.5 µm³',
      sliceCount: 64,
      totalScanVolume: 11.2,
      signalIntensityRange: '20 - 245 RFU',
      preprocessingAlgorithm: 'Gaussian Filtering / Dynamic Normalization',
      segmentationModel: '3D U-Net TissueSegmenter v0.9.0',
      surfaceAlgorithm: 'Marching Cubes Surface Mesh',
    },
    quantitative: {
      totalVolume: 11.2,
      healthyVolume: 5.75,
      damagedVolume: 5.45,
      transitionVolume: 1.34,
      unclassifiedVolume: 0.0,
      healthyPercent: 51.4,
      damagedPercent: 48.6,
      daiPercent: 48.6,
      daiCategory: 'high',
      damageLevel: 'severe',
      spatialPattern: 'diffuse',
      mostAffectedCoordinate: 'X: 30.2, Y: 89.4, Z: 24.1 (مركز الكتلة)',
      affectedFociCount: 3,
      averageConfidence: 91.5,
      uncertaintyLevel: 'moderate',
      measurements: [
        { id: 'C-201', type: 'Cell', volume: 105.0, x: 30.2, y: 89.4, z: 24.1, confidence: 92, status: 'needs_review', tissueClass: 'damaged' },
        { id: 'C-202', type: 'Cell', volume: 115.0, x: 36.0, y: 85.0, z: 27.0, confidence: 91, status: 'reviewed', tissueClass: 'healthy' },
      ],
    },
    review: {
      pathologistComment: 'مناطق ضمور واضحة بنسبة 48.6% مع تغيرات في بنية القنوات البنكرياسية. يوصى بمناقشة الحالة في اجتماع مجلس الأورام متعدد التخصصات (MDT).',
      preliminaryImpression: 'مؤشر الضمور الرقمي DAI مرتفع (48.6%) - يستلزم مطابقة مع التحاليل الخلوية المناعية.',
      recommendation: 'مراجعة فورية في اجتماع مجلس الأورام السريري لاتخاذ القرار الجراحي أو العلاجي المناسب.',
      reviewStatus: 'pending',
    },
    auditTrail: [
      {
        id: 'aud-33-1',
        sampleId: 'SMP-2026-033',
        action: 'اكتمال تحليل الذكاء الاصطناعي وبانتظار اعتماد الاستشاري',
        actorName: 'PanTissue AI Engine',
        actorRole: 'admin',
        timestamp: '2026-01-15T11:00:00Z',
      },
    ],
    isDraft: false,
    createdAt: '2026-01-15T08:15:00Z',
    updatedAt: '2026-01-15T11:00:00Z',
  },
];
